'use strict';
import keyMirror from "react/lib/keyMirror";

const Actions = keyMirror({

  RECEIVE_MANUFACTURERS_SUCCESS: null,
  GET_MAXAGE_SUCCESS: null,
  GET_ALL_ACTIVE_MANUFACTURERS_SUCCESS: null,
  GET_MANUFACTURERS_SUCCESS: null,
  GET_MODELS_SUCCESS: null,
  GET_SERIES_SUCCESS: null,
  GET_MODIFICATIONS_SUCCESS: null,
  GET_ALL_REGIONS_SUCCESS: null,
  STEP_CHANGED_SUCCESS: null,
  YEAR_CHANGED_SUCCESS: null,
  MANUFACTURER_CHANGED_SUCCESS: null,
  MODEL_CHANGED_SUCCESS: null,
  SERIA_CHANGED_SUCCESS: null,
  MODIFICATION_CHANGED_SUCCESS: null,
  REGION_CHANGED_SUCCESS: null,
  ODOMETER_CHANGED_SUCCESS: null,
  EMAIL_CHANGED_SUCCESS: null,
  DETERMINE_PRICE_SUCCESS: null
});


export default Actions;
