version: '2'
services:
  web:
    build: ./web
    ports:
      - "3020:3020"
    volumes:
      - ./code/web:/srv/www/
    command: bash -c "cd /srv/www && npm install -g nodemon && npm install && npm rebuild node-sass && npm run dev"
    links:
      - api
      - mongodb
  api:
    build: ./api
    ports:
      - "3030:3030"
    volumes:
      - ./code/api:/srv/www/
    command: bash -c "cd /srv/www && npm install -g nodemon && npm install && npm run populate-db && npm run dev"
    links:
      - mongodb

  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_PASS: password
